apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-migration-deployment
  namespace: prod-us
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-migration
  template:
    metadata:
      labels:
        app: db-migration
    spec:
      containers:
        - name: db
          image: minispace/db:latest
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "2"

