apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
spec:
  template:
    spec:
      containers:
      - name: db-migration
        image: maven:3.9.6-amazoncorretto-21-debian
      restartPolicy: Never
  backoffLimit: 2
