apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
spec:
  template:
    spec:
      containers:
      - name: db-migration
        image: minispace/db:latest
      restartPolicy: Never
  backoffLimit: 4
